version: 0.2
phases:
  install:
    runtime-versions:
      java: 21  # Ensures CodeBuild uses Java 21
  pre_build:
    commands:
      - echo "Checking Java version..."
      - java -version
      - mvn -version
  build:
    commands:
      - echo "Packaging JAR file..."
      - mvn clean package
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - target/EcomBE.jar
  discard-paths: yes