version: 0.2

phases:
  install:
    runtime-versions:
      java: 21  # This ensures AWS CodeBuild uses Java 21

  pre_build:
    commands:
      - echo "Setting Java 21 as default..."
      - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      - export PATH=$JAVA_HOME/bin:$PATH
      - echo "JAVA_HOME is set to: $JAVA_HOME"
      - java -version
      - mvn -version

  build:
    commands:
      - echo "Building the application..."
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - target/*.jar
  discard-paths: yes