version: 0.2
phases:
  install:
    runtime-versions:
      java: 21  # Ensure Java 21 is installed in CodeBuild
  pre_build:
    commands:
      - echo "Checking Java version..."
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - mvn -version
  build:
    commands:
      - echo "Packaging JAR file..."
      - mvn clean package
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - target/EcomBE.jar
  discard-paths: yes